### ISSUE TITLE
Player Controls on IMA ad Player

### ISSUE THREAD

**Issue by bcorvino** [glomex/vast-ima-player#22]
Hi,

Is there a way to implement standard player controls (play/pause, mute/unmute, elapsed time) on the adPlayer?

Is it a setting in your project or an ima setting?

Or do we have to roll our own?

If the answer is roll our own, I'm happy to contribute it back to the open source project.

Thanks!

**Comment by klipstein** [comment]
Hi @bcorvino. The short answer is: roll your own :)

We intentionally wanted to keep this library as low-level and as small as possible because we think that building a video-player user interface highly depends on individual needs and you often need to connect the UI to other parts of your environment (error handling, custom advertisment, custom animations/transitions, end-cards, ...) in order to fully control every part of the UI/UX.

At glomex we implemented a separate UI as overlay above the video-tag / IMA ad layer completely outside this library because we had to fulfill custom needs. If you want you can create a separate project that uses vast-ima-player as dependency but we don't want to maintain a separate UI stack.

To completely hide the Google IMA overlays you can do the following:

~~~
const adsRenderingSettings = new ima.AdsRenderingSettings();
adsRenderingSettings.uiElements = [];
const playerOptions = new PlayerOptions();
playerOptions.clickTrackingElement = adElementToRenderImaOverlayIn;

const player = new Player(
  ima, yourVideoElement, adElementToRenderImaOverlayIn,
  adsRenderingSettings, playerOptions
);
~~~

In case you want a more full fledged player with IMA integration I would suggest to have a look at https://github.com/openplayerjs/openplayerjs.

**Comment by bcorvino** [comment]
Hi,

Thanks for your reply. I'll look into rolling my own and I understand the reasoning.  I have previously implemented openplayerjs and have contributed to their ima integration, but I'm looking for something with a smaller footprint at this point, which is why your IMA library is so useful for us.

**Comment by klipstein** [comment]
Glad I was able to help.
